branch-defaults:
  3_groupC:
    environment: django-app-sarah
    group_suffix: null
  3_sarah:
    environment: null
    group_suffix: null
  default:
    environment: django-env
    group_suffix: null
  master:
    environment: django-env
global:
  application_name: renttestaws
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
