# Generated by Django 2.1.5 on 2019-02-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0001_initial'),
        ('property_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_request', models.DateField(blank=True)),
                ('duration_request', models.CharField(blank=True, max_length=80)),
                ('comments', models.TextField(blank=True)),
                ('tcd_acceptance', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UserManagement.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=150, null=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_application.Tenant'),
        ),
        migrations.AddField(
            model_name='application',
            name='lead_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant_application.Tenant'),
        ),
        migrations.AddField(
            model_name='application',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property_listing.Listing'),
        ),
    ]
