# Generated by Django 2.1.5 on 2019-02-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
        ('tenant_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='tcd_acceptance',
            new_name='has_accepted_tcd',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='payment_token',
        ),
        migrations.AddField(
            model_name='application',
            name='co_tenants',
            field=models.ManyToManyField(related_name='co_tenants_set', to='tenant_application.Tenant'),
        ),
        migrations.AddField(
            model_name='reference',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_contact_set', to='UserManagement.Contact'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_set', to='UserManagement.Contact'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_children',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_pets',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='has_verified_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='identification_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tenant',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('Drivers License', 'Drivers License'), ('Passport', 'Passport'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_18_plus',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_background_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_first_timer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_smoker',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_verified_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vehicle_make_and_model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='lead_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_tenant_set', to='tenant_application.Tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Contact'),
        ),
    ]
