# Generated by Django 2.1.5 on 2019-02-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20190211_1316'),
        ('UserManagement', '0002_auto_20190211_1007'),
    ]

    operations = [
    ]
