# Generated by Django 2.1.5 on 2019-02-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20190211_1327'),
        ('UserManagement', '0003_merge_20190212_1425'),
    ]

    operations = [
    ]
