# Generated by Django 2.1.5 on 2019-02-01 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price_low', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price_high', models.DecimalField(decimal_places=2, max_digits=9)),
                ('current_tenant_capacity', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tenant_feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('bathrooms', models.IntegerField()),
                ('tenant_capacity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('price', models.FloatField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('property_picture', models.CharField(blank=True, max_length=500, null=True)),
                ('landlord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_listing.Landlord')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_listing.PropertyManager'),
        ),
        migrations.AddField(
            model_name='listing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_listing.Property'),
        ),
    ]
