# Generated by Django 2.1.5 on 2019-02-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='first_time',
            new_name='is_first_timer',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='rental_wof',
            new_name='has_rental_wof',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='unit_title',
            new_name='has_unit_title',
        ),
    ]
